### ISSUE TITLE
Is this data no longer being updated?

### ISSUE THREAD

**Issue by arghgr** [washingtonpost/data-police-shootings#17]
I created twitter.com/poshootingsbot when this repository first went live, and recently noticed that the bot had stopped tweeting in February. Is this list no longer being updated?

**Comment by arghgr** [comment]
For anyone wondering the same thing, it looks like this repo is dead but they're still updating the site with the data in this JSON file: https://www.washingtonpost.com/graphics/policeshootings/daily_aggregate.json

**Comment by ScriptAutomate** [comment]
Yeah, the fact that the last dataset update to master was 496ed28e1ea01edb934be97f2aed7d5b701af7dc on **Feb. 19**. Yet, the website is querying a dataset that has been updated into April?

That JSON you are referencing only is a daily aggregate of police shootings, so it only provides a numerical digit as opposed to also the details of the shootings. All the open pull requests here are from 2016 - 2017, with this repository having zero history of actually having closed PRs (other than directly from the primary contributor).

Since 2016, all commits have been coming directly from @jmuyskens -- questions for him if he sees this: can you shed some light on how this repository is being managed / synced with the dataset being queried via The Washington Post data visualization page for this? Are any of these GitHub issues ever actually reviewed, or are any of the PRs actually reviewed either?

+Also Mentioning @stevenrich to the conversation also, since he is the other listed [Contributor](https://github.com/washingtonpost/data-police-shootings/graphs/contributors)

**Comment by jmuyskens** [comment]
This dataset is published from our internal database in an automated fashion using the Github API. I maintain the backend infrastructure but I'm not involved in the data entry process and I don't regularly check the issues on this repo. The JSON files used on our reader-facing interactive databases are also downstream of this same database. We don't merge PRs because they would just get overwritten then next time the dataset is published.

**Comment by ScriptAutomate** [comment]
Your README should include this information in a large notice at the top. Generally, when people open-source something, there is an assumption of _collaborative efforts and openness to feedback/contribution._

You are implying this is not the case, that you do not accept any PRs, and that you ignore most (if not all) opened issues of corrections due to this being a downstream mirror of some sort.

**Comment by bbneo** [comment]
I applaud you for challenging the lack of transparency here.
