### ISSUE TITLE
File format again XML, not CSV.

### ISSUE THREAD

**Issue by kalav** [washingtonpost/data-police-shootings#25]
You're again assigning .csv as a file extension to an XML file (as was done in a closed issue from 2016). .csv files are "flat" and contain only data and commas.

**Comment by jmuyskens** [comment]
Did you try downloading https://raw.githubusercontent.com/washingtonpost/data-police-shootings/master/fatal-police-shootings-data.csv ? This is a direct link to the CSV-formatted file. This is what our instructions in the README say to do.

If you download this page however https://github.com/washingtonpost/data-police-shootings/blob/master/fatal-police-shootings-data.csv you will get HTML, because it is not a direct link to the file but is instead a link to the Github view of the file. 

You aren't the only person who has been confused by this, but this is an issue with Github's interface, not with the data.
